# Generated by Django 5.2.6 on 2025-09-20 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='readingstatus',
            options={'verbose_name': 'Estado de Lectura', 'verbose_name_plural': 'Estados de Lectura'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Biografía del autor'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, help_text='Fecha de fallecimiento', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Nombre completo del autor', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture_url',
            field=models.URLField(blank=True, help_text='URL de la imagen del autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='api.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='URL de la portada'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='ISBN del libro', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, help_text='Número de páginas', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Fecha de publicación', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True, help_text='Sinopsis del libro'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Título del libro', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(help_text='Texto del comentario'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, help_text='País de origen', max_length=100),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='foundation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Año de fundación', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL del logo de la editorial'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Nombre de la editorial', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='finished_at',
            field=models.DateField(blank=True, help_text='Fecha de finalización de lectura', null=True),
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Calificación del 1 al 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='started_at',
            field=models.DateField(blank=True, help_text='Fecha de inicio de lectura', null=True),
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='status',
            field=models.CharField(choices=[('N', 'Not Started'), ('R', 'Reading'), ('C', 'Completed')], help_text='Estado de lectura', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(help_text='Texto de la reseña'),
        ),
    ]
