# Generated by Django 5.2.6 on 2025-09-24 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingstatus',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calificación del 0 al 5 (incrementos de 0.5)', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
