# Generated by Django 5.2.6 on 2025-09-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_readingstatus_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagen de portada personalizada de la estantería', null=True, upload_to='shelf_covers/'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='visibility',
            field=models.CharField(choices=[('public', 'Pública'), ('private', 'Privada')], default='public', help_text='Visibilidad de la estantería', max_length=10),
        ),
    ]
